### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by a5a5a9** [argoproj-labs/argocd-image-updater#159]
time="2021-02-25T22:01:22Z" level=debug msg="Using version constraint 'latest' when looking for a new tag" alias=msa_msa-ui application=xxxxxxxxxxxxxxxx image_tag="<nil>" registry=XXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com
time="2021-02-25T22:01:23Z" level=debug msg="found 1 from 1 tags eligible for consideration" image=XXXXXXX.dkr.ecr.us-east-1.amazonaws.com/xxx/xxx
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x18d7769]

goroutine 55 [running]:
github.com/argoproj-labs/argocd-image-updater/pkg/argocd.UpdateApplication(0x1db6178, 0x1fb4f60, 0xc00046a5c0, 0xc0004146d0, 0xc000427000, 0x1fcd101, 0x0, 0x0, 0x0, 0x0, ...)
/src/argocd-image-updater/pkg/argocd/update.go:137 +0xb09
main.runImageUpdater.func1(0xc00011c870, 0xc000418c40, 0xc0003f0590, 0xc00034d9e0, 0xc000515101, 0xc0003f0594, 0xc000500270, 0xb, 0x0, 0x0, ...)
/src/argocd-image-updater/cmd/main.go:132 +0x18f
created by main.runImageUpdater
/src/argocd-image-updater/cmd/main.go:129 +0x8f6

**Comment by a5a5a9** [comment]
.
